import { RestaurantNavItem, RestaurantNavSection } from './restaurant-nav.model';

export const RESTAURANT_NAV_SECTIONS: RestaurantNavSection[] = [
  {
    id: 'overview',
    labelAr: 'الرئيسية',
    labelEn: 'Overview',
    icon: 'lucideLayoutDashboard',
    items: [
      {
        id: 'restaurant-overview',
        labelAr: 'نظرة عامة',
        labelEn: 'Overview',
        route: '/restaurant/overview',
        icon: 'lucideLayoutDashboard',
      },
      {
        id: 'restaurant-analytics',
        labelAr: 'التحليلات والأداء',
        labelEn: 'Analytics & performance',
        route: '/restaurant/overview/analytics',
        icon: 'lucideChartNoAxesCombined',
      },
      {
        id: 'restaurant-operations-summary',
        labelAr: 'تشغيل اليوم',
        labelEn: 'Daily operations',
        route: '/restaurant/overview/operations',
        icon: 'lucideGauge',
        badge: 3,
      },
      {
        id: 'restaurant-finance-summary',
        labelAr: 'النظرة المالية',
        labelEn: 'Finance overview',
        route: '/restaurant/overview/finance',
        icon: 'lucideWallet',
      },
      {
        id: 'restaurant-quality-summary',
        labelAr: 'الجودة والأداء',
        labelEn: 'Quality & performance',
        route: '/restaurant/overview/quality',
        icon: 'lucideStar',
      },
      {
        id: 'restaurant-activity',
        labelAr: 'مركز المتابعة',
        labelEn: 'Activity center',
        route: '/restaurant/overview/activity',
        icon: 'lucideListTodo',
        badge: 6,
      },
    ],
  },
  {
    id: 'orders',
    labelAr: 'الطلبات',
    labelEn: 'Orders',
    icon: 'lucideClipboardList',
    items: [
      {
        id: 'daily-orders',
        labelAr: 'طلبات اليوم',
        labelEn: 'Daily orders',
        route: '/restaurant/orders/daily',
        icon: 'lucideCalendarDays',
      },
      {
        id: 'pending-confirmation',
        labelAr: 'بانتظار التأكيد',
        labelEn: 'Pending confirmation',
        route: '/restaurant/orders/pending-confirmation',
        icon: 'lucideClock',
        badge: 2,
      },
      {
        id: 'upcoming-24h',
        labelAr: 'تحضير 24 ساعة',
        labelEn: 'Upcoming 24h prep',
        route: '/restaurant/orders/upcoming-24h',
        icon: 'lucidePackage',
        badge: 1,
      },
      {
        id: 'labels-barcodes',
        labelAr: 'الملصقات والباركود',
        labelEn: 'Labels & barcodes',
        route: '/restaurant/orders/labels',
        icon: 'lucideQrCode',
      },
      {
        id: 'order-handover',
        labelAr: 'تسليم الطلبات',
        labelEn: 'Order handover',
        route: '/restaurant/orders/handover',
        icon: 'lucideScanBarcode',
      },
      {
        id: 'archived-orders',
        labelAr: 'أرشيف الطلبات',
        labelEn: 'Orders archive',
        route: '/restaurant/orders/archive',
        icon: 'lucideArchive',
      },
    ],
  },
  {
    id: 'operations',
    labelAr: 'التشغيل',
    labelEn: 'Operations',
    icon: 'lucideBriefcaseBusiness',
    items: [
      {
        id: 'menu',
        labelAr: 'القوائم والوجبات',
        labelEn: 'Menus & meals',
        route: '/restaurant/operations/menu',
        icon: 'lucideUtensilsCrossed',
      },
      {
        id: 'ingredients',
        labelAr: 'مكونات المطعم',
        labelEn: 'Restaurant ingredients',
        route: '/restaurant/operations/ingredients',
        icon: 'lucideCookingPot',
      },
      {
        id: 'pricing',
        labelAr: 'التسعير',
        labelEn: 'Pricing',
        route: '/restaurant/operations/pricing',
        icon: 'lucideBadgeDollarSign',
      },
      {
        id: 'service-regions',
        labelAr: 'مناطق الخدمة',
        labelEn: 'Service regions',
        route: '/restaurant/operations/service-regions',
        icon: 'lucideMapPinned',
      },
      {
        id: 'capacity',
        labelAr: 'السعة اليومية',
        labelEn: 'Daily capacity',
        route: '/restaurant/operations/capacity',
        icon: 'lucideGauge',
      },
      {
        id: 'availability',
        labelAr: 'التوفر وحالة الانشغال',
        labelEn: 'Availability & busy status',
        route: '/restaurant/operations/availability',
        icon: 'lucideActivity',
      },
    ],
  },
  {
    id: 'delivery-quality',
    labelAr: 'التوصيل والجودة',
    labelEn: 'Delivery & quality',
    icon: 'lucideTruck',
    items: [
      {
        id: 'drivers',
        labelAr: 'السائقون',
        labelEn: 'Drivers',
        route: '/restaurant/delivery/drivers',
        icon: 'lucideUsers',
      },
      {
        id: 'ratings',
        labelAr: 'التقييمات',
        labelEn: 'Ratings',
        route: '/restaurant/quality/ratings',
        icon: 'lucideStar',
      },
    ],
  },
  {
    id: 'finance',
    labelAr: 'المالية',
    labelEn: 'Finance',
    icon: 'lucideWallet',
    items: [
      {
        id: 'dues',
        labelAr: 'المستحقات والعمولات',
        labelEn: 'Dues & commissions',
        route: '/restaurant/finance/dues',
        icon: 'lucideHandCoins',
      },
      {
        id: 'deductions',
        labelAr: 'الخصومات والتسويات',
        labelEn: 'Deductions & adjustments',
        route: '/restaurant/finance/deductions',
        icon: 'lucideReceipt',
      },
      {
        id: 'invoices',
        labelAr: 'الفواتير الشهرية',
        labelEn: 'Monthly invoices',
        route: '/restaurant/finance/invoices',
        icon: 'lucideFileText',
      },
      {
        id: 'payouts',
        labelAr: 'الدفعات والتحويلات',
        labelEn: 'Payouts & transfers',
        route: '/restaurant/finance/payouts',
        icon: 'lucideLandmark',
      },
      {
        id: 'statements',
        labelAr: 'كشف الحساب',
        labelEn: 'Account statements',
        route: '/restaurant/finance/statements',
        icon: 'lucideScrollText',
      },
      {
        id: 'reports',
        labelAr: 'التقارير المالية',
        labelEn: 'Financial reports',
        route: '/restaurant/finance/reports',
        icon: 'lucideChartColumn',
      },
    ],
  },
];

export const RESTAURANT_SETTINGS_ITEM: RestaurantNavItem = {
  id: 'settings',
  labelAr: 'إعدادات المطعم',
  labelEn: 'Restaurant settings',
  route: '/restaurant/settings',
  icon: 'lucideSettings',
};
